version: '3.8'

services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    env_file:
      - .env
    expose:
      - "3000" # only accessible within Docker network
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nuxt-app
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
